# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('posted_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=1000)),
                ('posted_date', models.DateTimeField(verbose_name='date commented')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
